import { TCGSet, BountyRank, SpinReward } from "@/types";

export const BOUNTY_RANKS: BountyRank[] = [
  {
    name: "East Blue",
    minSpent: 0,
    discount: 0,
    icon: "🌊",
    image: "/images/ranks/east-blue.png",
    color: "#4a90d9",
  },
  {
    name: "Paradise",
    minSpent: 5000,
    discount: 3,
    icon: "⚓",
    image: "/images/ranks/paradise.png",
    color: "#f5a623",
  },
  {
    name: "New World",
    minSpent: 15000,
    discount: 5,
    icon: "🔥",
    color: "#e74c3c",
  },
  {
    name: "Yonko",
    minSpent: 50000,
    discount: 8,
    icon: "👑",
    image: "/images/ranks/yonko.png",
    color: "#ffd700",
  },
];

// Helper to create set data with box pricing
function makeSet(
  id: string, name: string, slug: string, code: string, description: string,
  boxCount: number, pricePerBox: number, stock: number, status: "in-stock" | "pre-order" | "sold-out",
  releaseDate: string, packsPerBox: number, cardsPerPack: number,
  islandName: string, islandColor: string, islandGradient: string,
  islandDescription: string, islandArc: string, islandKeyCharacters: string[],
  category?: "booster" | "extra" | "premium" | "starter",
): TCGSet {
  return {
    id, name, slug, code, description,
    image: `/images/sets/${id}.png`,
    boxCount, pricePerBox, stock, status, releaseDate,
    packsPerBox, cardsPerPack,
    category,
    islandTheme: {
      name: islandName,
      color: islandColor,
      gradient: islandGradient,
      description: islandDescription,
      arc: islandArc,
      keyCharacters: islandKeyCharacters,
    },
  };
}

export const SAMPLE_SETS: TCGSet[] = [
  // === BOOSTER PACKS (JP: 24 packs/box, 6 cards/pack) ===
  makeSet("op01", "Romance Dawn", "romance-dawn", "OP-01",
    "ชุดแรกของ One Piece Card Game! เริ่มต้นการผจญภัยกับลูฟี่และหมวกฟาง",
    12, 2200, 3, "in-stock", "2022-07-22", 24, 6,
    "Foosha Village", "#e74c3c", "from-red-900 via-red-700 to-orange-500",
    "A quiet coastal village on Dawn Island in the East Blue, where Monkey D. Luffy grew up and set sail to become King of the Pirates.",
    "Romance Dawn Arc",
    ["Monkey D. Luffy", "Shanks", "Makino", "Woop Slap"],
    "booster"),
  makeSet("op02", "Paramount War", "paramount-war", "OP-02",
    "สงครามสุดยอดแห่ง Marineford! มาพร้อมไวท์เบียร์ด, เอส และพลเรือเอก",
    12, 2200, 2, "in-stock", "2022-11-04", 24, 6,
    "Marineford", "#2c3e50", "from-slate-900 via-blue-900 to-indigo-700",
    "The Marine Headquarters fortress located at the tip of the Marineford Bay, site of the most devastating war in modern history — the battle to save Portgas D. Ace.",
    "Marineford Arc (Summit War)",
    ["Edward Newgate (Whitebeard)", "Portgas D. Ace", "Monkey D. Garp", "Sengoku", "Aokiji", "Kizaru", "Akainu", "Marco"],
    "booster"),
  makeSet("op03", "Pillars of Strength", "pillars-of-strength", "OP-03",
    "นักรบผู้แข็งแกร่งมารวมตัว! เหล่าชิจิบุไคและนักสู้ระดับตำนาน",
    12, 2400, 4, "in-stock", "2023-02-11", 24, 6,
    "Dressrosa", "#8e44ad", "from-purple-900 via-purple-700 to-pink-500",
    "A vibrant kingdom ruled by the Shichibukai Donquixote Doflamingo, known for its flower fields, colosseum of warriors, and the secret underground trade of Devil Fruits and weapons.",
    "Dressrosa Arc",
    ["Donquixote Doflamingo", "Trafalgar Law", "Issho (Fujitora)", "Sabo", "Cavendish", "Bartholomew Kuma", "Boa Hancock"],
    "booster"),
  makeSet("op04", "Kingdoms of Intrigue", "kingdoms-of-intrigue", "OP-04",
    "แผนลับและพลังที่ซ่อนเร้น! CP0 กับกองทัพปฏิวัติ",
    12, 2400, 5, "in-stock", "2023-05-27", 24, 6,
    "Enies Lobby", "#3498db", "from-cyan-900 via-blue-700 to-teal-500",
    "The World Government's judicial island and Gateway to the New World, perpetually bathed in daylight and home to the fearsome CP9 and the Tower of Justice.",
    "Enies Lobby Arc (Water 7 Saga)",
    ["Rob Lucci", "Spandam", "Kaku", "Blueno", "CP9", "Nico Robin", "Monkey D. Luffy"],
    "booster"),
  makeSet("op05", "Awakening of the New Era", "awakening-of-the-new-era", "OP-05",
    "ยุคใหม่เริ่มต้น! Worst Generation ตื่นขึ้นพร้อมพลังใหม่",
    12, 2600, 8, "in-stock", "2023-08-26", 24, 6,
    "Wano Country", "#27ae60", "from-emerald-900 via-green-700 to-lime-500",
    "An isolated, samurai-ruled nation sealed off from the world and subjugated by Kaido of the Beasts, whose liberation marks the dawn of a new era on the seas.",
    "Wano Country Arc",
    ["Eustass Kid", "Killer", "Roronoa Zoro", "Trafalgar Law", "Kaido", "Big Mom", "Yamato", "Momonosuke"],
    "booster"),
  makeSet("op06", "Wings of the Captain", "wings-of-the-captain", "OP-06",
    "ปีกของราชาโจรสลัด! โซโร ซันจิ และพันธมิตรที่แข็งแกร่ง",
    12, 2600, 6, "in-stock", "2023-11-25", 24, 6,
    "Whole Cake Island", "#f39c12", "from-amber-900 via-yellow-700 to-orange-400",
    "The fantastical island ruled by Charlotte Linlin (Big Mom), built entirely of edible materials, where Sanji's past was revealed and the Straw Hats fought to survive.",
    "Whole Cake Island Arc",
    ["Vinsmoke Sanji", "Roronoa Zoro", "Charlotte Linlin (Big Mom)", "Vinsmoke Judge", "Reiju", "Pudding", "Katakuri"],
    "booster"),
  makeSet("op07", "500 Years in the Future", "500-years-in-the-future", "OP-07",
    "ล่วงหน้า 500 ปี! ค้นพบความลับของ Egghead Island",
    12, 2800, 10, "in-stock", "2024-02-24", 24, 6,
    "Egghead Island", "#1abc9c", "from-teal-900 via-teal-600 to-cyan-400",
    "A futuristic laboratory island belonging to Dr. Vegapunk, described as the island that is 500 years ahead of its time and packed with cutting-edge Marine science.",
    "Egghead Arc",
    ["Dr. Vegapunk", "Sentomaru", "Seraphim", "Rob Lucci", "Monkey D. Luffy", "Bonney", "Kizaru", "Saturn"],
    "booster"),
  makeSet("op08", "Two Legends", "two-legends", "OP-08",
    "สองตำนานปะทะ! การดวลสุดยอดของสองคู่ปรับระดับตำนาน",
    12, 3200, 15, "in-stock", "2024-05-25", 24, 6,
    "God Valley", "#c0392b", "from-red-950 via-red-800 to-amber-600",
    "A legendary island that was erased from all maps after the fateful battle 38 years ago where the Rocks Pirates were defeated by Gol D. Roger and Monkey D. Garp.",
    "God Valley Incident (Flashback)",
    ["Gol D. Roger", "Monkey D. Garp", "Rocks D. Xebec", "Edward Newgate (Whitebeard)", "Charlotte Linlin (Big Mom)", "Kaido", "Shiki"],
    "booster"),
  makeSet("op09", "Emperors in the New World", "emperors-in-the-new-world", "OP-09",
    "จักรพรรดิทั้งสี่! พลังเต็มพิกัดของ Shanks, Blackbeard, Big Mom, Kaido",
    12, 3200, 18, "in-stock", "2024-08-31", 24, 6,
    "Onigashima", "#e91e63", "from-pink-950 via-pink-700 to-rose-400",
    "Kaido's skull-shaped stronghold island off the coast of Wano Country, seat of the Beasts Pirates and site of the cataclysmic raid that toppled two Emperors in one night.",
    "Wano Country Arc (Onigashima Raid)",
    ["Kaido", "Charlotte Linlin (Big Mom)", "Shanks", "Marshall D. Teach (Blackbeard)", "Monkey D. Luffy", "Yamato", "Marco"],
    "booster"),
  makeSet("op10", "Royal Blood", "royal-blood", "OP-10",
    "สายเลือดแห่งราชวงศ์! World Nobles, Vivi และความลับ Void Century",
    12, 3200, 20, "in-stock", "2024-11-30", 24, 6,
    "Mary Geoise", "#9b59b6", "from-violet-950 via-purple-700 to-fuchsia-500",
    "The Holy Land atop the Red Line, seat of the World Government and home of the Celestial Dragons, who claim divine lineage and lord over the world from its highest point.",
    "Reverie Arc / Egghead Arc",
    ["Im", "Five Elders", "Donquixote Mjosgard", "Nefertari Vivi", "Sabo", "Jewelry Bonney", "Cobra Nefertari"],
    "booster"),
  makeSet("op11", "A Fist of Divine Speed", "a-fist-of-divine-speed", "OP-11",
    "หมัดแห่งความเร็วเทพ! นักสู้ที่เร็วที่สุดปะทะกัน",
    12, 3400, 24, "in-stock", "2025-03-01", 24, 6,
    "Sabaody Archipelago", "#e67e22", "from-orange-950 via-orange-700 to-yellow-500",
    "A large mangrove archipelago just below the Red Line where pirates gather before entering the New World, famous for its Yarukiman mangrove trees and the Auction House.",
    "Sabaody Archipelago Arc",
    ["Silvers Rayleigh", "Shakuyaku", "Kizaru", "Sentomaru", "Monkey D. Luffy", "Roronoa Zoro", "Boa Hancock"],
    "booster"),
  makeSet("op12", "Legacy of the Master", "legacy-of-the-master", "OP-12",
    "มรดกของปรมาจารย์! อาจารย์ระดับตำนานและศิษย์ผู้สืบทอด",
    12, 3400, 20, "in-stock", "2025-05-31", 24, 6,
    "Zou", "#795548", "from-stone-900 via-amber-800 to-yellow-600",
    "An enormous, ever-wandering elephant named Zunesha that carries a kingdom of Minks on its back — a living island holding ancient secrets of the Void Century and the poneglyphs.",
    "Zou Arc",
    ["Nekomamushi", "Inuarashi", "Raizo", "Momonosuke", "Zunesha", "Silvers Rayleigh", "Pedro"],
    "booster"),
  makeSet("op13", "Carrying On His Will", "carrying-on-his-will", "OP-13",
    "ชุดฉลองครบรอบ 3 ปี! สืบทอดเจตนารมณ์ของราชาโจรสลัด",
    12, 3400, 30, "in-stock", "2025-08-23", 24, 6,
    "Loguetown", "#2196f3", "from-blue-950 via-blue-700 to-sky-400",
    "The town at the beginning and the end — the birthplace and execution site of Gol D. Roger, King of the Pirates, where his last words ignited the Great Pirate Era.",
    "Loguetown Arc",
    ["Gol D. Roger", "Smoker", "Tashigi", "Buggy", "Alvida", "Monkey D. Luffy", "Dragon"],
    "booster"),
  makeSet("op14", "The Azure Sea's Seven", "the-azure-seas-seven", "OP-14",
    "เจ็ดนักรบแห่งท้องทะเลครามรวมตัว!",
    12, 3400, 36, "in-stock", "2025-11-22", 24, 6,
    "Fish-Man Island", "#00bcd4", "from-cyan-950 via-cyan-700 to-sky-400",
    "An underwater kingdom 10,000 meters below the surface, home to the Fish-Men and Merfolk, and gateway to the New World beneath the Red Line.",
    "Fish-Man Island Arc",
    ["Neptune", "Shirahoshi", "Jinbe", "Hody Jones", "Vander Decken IX", "Monkey D. Luffy", "Tiger Fisher"],
    "booster"),
  makeSet("op15", "Adventure on Kami's Island", "adventure-on-kamis-island", "OP-15",
    "ผจญภัยบนเกาะแห่งพระเจ้า! สกายเปียและเทพเจ้าเอเนล",
    12, 3400, 0, "pre-order", "2026-02-28", 24, 6,
    "Skypiea", "#ffc107", "from-amber-900 via-yellow-600 to-amber-300",
    "A sky island 10,000 meters above the sea, ruled by God Eneru and inhabited by the Skypieans and Shandorians, reached by sailing through the Knock Up Stream.",
    "Skypiea Arc",
    ["Eneru", "Conis", "Wyper", "Gan Fall", "Nola", "Monkey D. Luffy", "Nami"],
    "booster"),

  // === EXTRA BOOSTERS (JP: 24 packs/box, 6 cards/pack) ===
  makeSet("eb01", "Memorial Collection", "memorial-collection", "EB-01",
    "คอลเลกชันแห่งความทรงจำ! ตัวละครและช่วงเวลาสุดประทับใจ",
    12, 3200, 3, "in-stock", "2024-01-27", 24, 6,
    "Marineford", "#ff69b4", "from-pink-900 via-pink-500 to-rose-300",
    "The Marine Headquarters fortress, site of the Summit War and the most pivotal moment in modern history — a battle that reshaped the entire world and is etched into every pirate's memory.",
    "Marineford Arc (Summit War)",
    ["Monkey D. Luffy", "Portgas D. Ace", "Edward Newgate (Whitebeard)", "Shanks", "Sengoku", "Marco", "Jinbe"],
    "extra"),
  makeSet("eb02", "Anime 25th Collection", "anime-25th-collection", "EB-02",
    "ฉลอง 25 ปีอนิเมะ One Piece! การ์ดพิเศษจากฉากสุดคลาสสิก",
    12, 3400, 8, "in-stock", "2025-01-25", 24, 6,
    "Laugh Tale", "#ff5722", "from-orange-900 via-red-600 to-amber-500",
    "The legendary island at the end of the Grand Line, said to be the final destination of the Pirate King Gol D. Roger, where the One Piece treasure lies hidden and the true history of the world sleeps.",
    "Final Arc (Legend / Flashback)",
    ["Gol D. Roger", "Silvers Rayleigh", "Scopper Gaban", "Crocus", "Monkey D. Luffy", "Nami", "Roronoa Zoro"],
    "extra"),
  makeSet("eb03", "One Piece Heroines Edition", "heroines-edition", "EB-03",
    "สาวๆ แห่ง One Piece! นามิ โรบิน แฮนค็อก และฮีโร่หญิงทุกคน",
    12, 3600, 14, "in-stock", "2025-10-25", 24, 6,
    "Amazon Lily", "#e91e63", "from-rose-900 via-pink-600 to-fuchsia-400",
    "An isolated island of warrior women in the Calm Belt, ruled by the Pirate Empress Boa Hancock and home to the all-female Kuja tribe, famous for their deadly snake-based weapons.",
    "Amazon Lily Arc",
    ["Boa Hancock", "Boa Sandersonia", "Boa Marigold", "Nami", "Nico Robin", "Nefertari Vivi", "Jewelry Bonney"],
    "extra"),

  // === PREMIUM BOOSTERS (JP: 10 packs/box, 10 cards/pack) ===
  makeSet("prb01", "ONE PIECE CARD THE BEST", "the-best", "PRB-01",
    "คอลเลกชันพรีเมียม! รวมการ์ดเด็ดพร้อม Special Art",
    10, 4200, 2, "in-stock", "2024-07-27", 10, 10,
    "Laugh Tale", "#ffd700", "from-yellow-900 via-amber-600 to-yellow-400",
    "The legendary island at the end of the Grand Line where Gol D. Roger hid the One Piece, the greatest treasure in the world — the destination every pirate dreams of reaching.",
    "Across All Arcs (Grand Line)",
    ["Gol D. Roger", "Monkey D. Luffy", "Roronoa Zoro", "Nami", "Nico Robin", "Shanks", "Edward Newgate (Whitebeard)"],
    "premium"),
  makeSet("prb02", "ONE PIECE CARD THE BEST Vol.2", "the-best-vol2", "PRB-02",
    "พรีเมียม Vol.2! การ์ด Alternate Art สุดอลังการ",
    10, 4200, 0, "pre-order", "2025-07-26", 10, 10,
    "Raftel (New World)", "#ff6f00", "from-orange-950 via-amber-700 to-orange-400",
    "The second half of the Grand Line known as the New World, the most treacherous sea on the planet dominated by the Four Emperors, where only the mightiest pirates survive.",
    "New World (Post-Timeskip)",
    ["Monkey D. Luffy", "Roronoa Zoro", "Shanks", "Marshall D. Teach (Blackbeard)", "Trafalgar Law", "Eustass Kid", "Silvers Rayleigh"],
    "premium"),
];

export const SPIN_REWARDS: SpinReward[] = [
  { label: "Free Sleeve Pack", color: "#e74c3c", probability: 0.3 },
  { label: "5% Off Next Order", color: "#ffd700", probability: 0.25 },
  { label: "Free Sticker Set", color: "#3498db", probability: 0.2 },
  { label: "10% Off Next Order", color: "#27ae60", probability: 0.1 },
  { label: "Mystery Promo Card", color: "#8e44ad", probability: 0.1 },
  { label: "Try Again", color: "#95a5a6", probability: 0.05 },
];

export const getRankBySpent = (totalSpent: number): BountyRank => {
  const sorted = [...BOUNTY_RANKS].sort((a, b) => b.minSpent - a.minSpent);
  return sorted.find((r) => totalSpent >= r.minSpent) || BOUNTY_RANKS[0];
};

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat("th-TH").format(price);
};
